# Generated by Django 3.1.7 on 2021-03-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0002_auto_20210308_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='revoke_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='revoked_by',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
