# Generated by Django 3.1.7 on 2021-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0004_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
