# Generated by Django 3.1.7 on 2021-03-13 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0005_auto_20210311_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Help.usermodel'),
        ),
    ]
