# Generated by Django 3.1.7 on 2021-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0008_ticketreply_reply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_open_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='categrories',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Fronted', 'Frontend'), ('Android', 'Android')], max_length=100),
        ),
    ]
