# Generated by Django 3.1.7 on 2021-03-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0010_ticketmodel_open_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='open_by',
        ),
    ]
