# Generated by Django 3.1.7 on 2021-03-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0011_remove_ticketmodel_open_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_closed_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_opened_by',
            field=models.IntegerField(null=True),
        ),
    ]
