# Generated by Django 3.1.7 on 2021-03-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0012_auto_20210318_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='user',
        ),
    ]
