# Generated by Django 3.1.7 on 2021-03-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0013_remove_ticketreply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Help.usermodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('Business team', 'Business team'), ('Developer', 'Developer'), ('Admin', 'Admin'), ('ML', 'ML'), ('Quality Check', 'Quality Check'), ('Tester', 'Tester')], max_length=100),
        ),
    ]
