# Generated by Django 3.1.7 on 2021-03-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Help', '0014_auto_20210319_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='rply_to_rply',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='rply_to_rply_date',
            field=models.DateTimeField(null=True),
        ),
    ]
